### PR TITLE
Require CRLF line endings in request line and headers

### LINKED ISSUE #137: CR incorrectly permitted within header values
WEBrick allows CR (`\r`) within header values. RFC 9110 says not to do this:
> Field values containing CR, LF, or NUL characters are invalid and dangerous, due to the varying ways that implementations might parse and interpret those characters; a recipient of CR, LF, or NUL within a field value MUST either reject the message or replace each of those characters with SP before further processing or forwarding of that message.

The suggested fix here would be to reject requests with headers containing bare CR.

### PR DESCRIPTION
**Pull request by jeremyevans**
Disallow bare CR, LF, NUL in header and request lines. Tighten parsing of request lines to only allow single spaces, as specified in the RFCs.

Forcing this RFC-compliant behavior breaks a lot of tests, so fix the tests to correctly use CRLF instead of LF for requests (other than the specific checks for handling of bad requests).

Fixes #137

### CODE REVIEW

File: lib/webrick/httprequest.rb [hunk 1]
```diff
@@ -458,7 +458,7 @@ def read_request_line(socket)
       end
 
       @request_time = Time.now
-      if /^(\S+)\s+(\S++)(?:\s+HTTP\/(\d+\.\d+))?\r?\n/mo =~ @request_line
+      if /^(\S+) (\S++)(?: HTTP\/(\d+\.\d+))?\r\n/mo =~ @request_line
```
Comment (kenballus) [inline lib/webrick/httprequest.rb:461]: I think the old behavior is technically RFC-compliant.

RFC 9112 section 3:
> Although the request-line grammar rule requires that each of the component elements be separated by a single SP octet, recipients MAY instead parse on whitespace-delimited word boundaries and, aside from the CRLF terminator, treat any form of whitespace as the SP separator while ignoring preceding or trailing whitespace; such whitespace includes one or more of the following octets: SP, HTAB, VT (%x0B), FF (%x0C), or bare CR. However, lenient parsing can result in request smuggling security vulnerabilities if there are multiple recipients of the message and each has its own unique interpretation of robustness (see Section 11.2).

That said, this isn't a bad change. Apache rejects request lines that use whitespace other than a single SP octet, so I don't think you'll break compatibility with any clients by tightening this up.

File: lib/webrick/httprequest.rb [hunk 2]
```diff
@@ -471,7 +471,7 @@ def read_request_line(socket)
     def read_header(socket)
       if socket
         while line = read_line(socket)
-          break if /\A(#{CRLF}|#{LF})\z/om =~ line
+          break if /\A#{CRLF}\z/om =~ line
```
Comment (kenballus) [inline lib/webrick/httprequest.rb:474]: Similarly, breaking lines on bare LF is allowed by the RFCs, so the old behavior was not a violation. From RFC 9112, section 2.2:
> Although the line terminator for the start-line and fields is the sequence CRLF, a recipient MAY recognize a single LF as a line terminator and ignore any preceding CR.

Again, many popular servers (Apache, Lighttpd, Node.js, Passenger, Puma) require CRLF line endings, so you're unlikely to break compatibility by joining that club.

**Comment by jeremyevans** [comment]
@kenballus Thank you very much for your review.  Since the RFCs do not require (MAY not MUST) the loose behavior, I would feel better about making things strict in order to reduce the chance of security issues, especially since other web servers are similarly strict.

**Comment by kenballus** [comment]
Agreed. LGTM.

File: test/webrick/test_httprequest.rb [hunk 3]
```diff
@@ -11,7 +11,7 @@ def teardown
 
   def test_simple_request
     msg = <<-_end_of_message_
-GET /
+GET /\r
```
Comment (ioquatix) [inline test/webrick/test_httprequest.rb:14]: Shouldn't this be `\r\n`?

File: test/webrick/test_httprequest.rb [hunk 4]
```diff
@@ -77,7 +77,7 @@ def test_request_uri_too_large
     _end_of_message_
     req = WEBrick::HTTPRequest.new(WEBrick::Config::HTTP)
     assert_raise(WEBrick::HTTPStatus::RequestURITooLarge){
-      req.parse(StringIO.new(msg.gsub(/^ {6}/, "")))
+      req.parse(StringIO.new(msg.gsub(/^ {6}/, "").gsub("\n", "\r\n")))
```
Comment (ioquatix) [inline test/webrick/test_httprequest.rb:80]: There is a lot of duplicated setup. Would it make sense to extract it into a helper?

**Review by ioquatix — APPROVED** [review]
Basically looks okay to me, but these tests look kind of crufty in general (not the fault of the PR).

File: test/webrick/test_httprequest.rb (hunk 3 above)
Comment (jeremyevans) [reply test/webrick/test_httprequest.rb:14]: The `\n` comes from the line ending (it's a heredoc).

File: test/webrick/test_httprequest.rb (hunk 4 above)
Comment (jeremyevans) [reply test/webrick/test_httprequest.rb:80]: Sure.  If someone wants to work on cleaning up the specs in a later PR, that would be great.
